using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Validify.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ValidatorRegistrationGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FullyQualified = SymbolDisplayFormat.FullyQualifiedFormat;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var local = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetLocalValidators(ctx))
            .Where(static a => a.Count > 0)
            .Collect();

        context.RegisterSourceOutput(local, static (spc, locals) => Emit(spc, Flatten(locals)));
    }

    private static EquatableArray<ValidatorRegistration> GetLocalValidators(GeneratorSyntaxContext ctx)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol symbol)
            return EquatableArray<ValidatorRegistration>.Empty;

        if (!IsConcreteCandidate(symbol))
            return EquatableArray<ValidatorRegistration>.Empty;

        var builder = ImmutableArray.CreateBuilder<ValidatorRegistration>();
        foreach (var serviceType in GetValidatorServiceTypes(symbol))
            builder.Add(new ValidatorRegistration(serviceType, symbol.ToDisplayString(FullyQualified)));

        return new EquatableArray<ValidatorRegistration>(builder.ToImmutable());
    }

    /// <summary>True when the type can be instantiated and registered as a validator.</summary>
    private static bool IsConcreteCandidate(INamedTypeSymbol symbol) =>
        symbol is { TypeKind: TypeKind.Class, IsAbstract: false, IsStatic: false, IsGenericType: false };

    /// <summary>Fully-qualified <c>IValidator&lt;T&gt;</c> strings this type implements.</summary>
    private static IEnumerable<string> GetValidatorServiceTypes(INamedTypeSymbol symbol)
    {
        foreach (var iface in symbol.AllInterfaces)
        {
            if (iface is { MetadataName: "IValidator`1", TypeArguments.Length: 1 } &&
                iface.ContainingNamespace.ToDisplayString() == "FluentValidation")
            {
                yield return iface.ToDisplayString(FullyQualified);
            }
        }
    }

    private static EquatableArray<ValidatorRegistration> Flatten(ImmutableArray<EquatableArray<ValidatorRegistration>> groups)
    {
        var builder = ImmutableArray.CreateBuilder<ValidatorRegistration>();
        foreach (var group in groups)
            builder.AddRange(group.AsImmutableArray());
        return new EquatableArray<ValidatorRegistration>(builder.ToImmutable());
    }

    private static void Emit(SourceProductionContext context, EquatableArray<ValidatorRegistration> registrations)
    {
        var ordered = registrations.AsImmutableArray()
            .Distinct()
            .OrderBy(static r => r.ServiceType, System.StringComparer.Ordinal)
            .ThenBy(static r => r.ImplementationType, System.StringComparer.Ordinal)
            .ToImmutableArray();

        if (ordered.Length == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Validify");
        sb.AppendLine("{");
        sb.AppendLine("    using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Auto-generated FluentValidation validator registrations.</summary>");
        sb.AppendLine("    public static class ValidifyGeneratedRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers every discovered FluentValidation validator.</summary>");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddValidifyValidators(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine("            global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped)");
        sb.AppendLine("        {");
        foreach (var r in ordered)
        {
            sb.AppendLine(
                $"            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({r.ServiceType}), typeof({r.ImplementationType}), lifetime));");
        }
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ValidifyGeneratedRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
