using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Validify.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ValidatorRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => { });

        var registrations = context.CompilationProvider
            .Select(static (_, _) => EquatableArray<ValidatorRegistration>.Empty);

        context.RegisterSourceOutput(registrations, static (spc, regs) => Emit(spc, regs));
    }

    private static void Emit(SourceProductionContext context, EquatableArray<ValidatorRegistration> registrations)
    {
        var ordered = registrations.AsImmutableArray()
            .Distinct()
            .OrderBy(static r => r.ServiceType, System.StringComparer.Ordinal)
            .ThenBy(static r => r.ImplementationType, System.StringComparer.Ordinal)
            .ToImmutableArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Auto-generated FluentValidation validator registrations.</summary>");
        sb.AppendLine("    public static class ValidifyGeneratedRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers every discovered FluentValidation validator.</summary>");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddValidifyValidators(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine("            global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped)");
        sb.AppendLine("        {");
        foreach (var r in ordered)
        {
            sb.AppendLine(
                $"            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({r.ServiceType}), typeof({r.ImplementationType}), lifetime));");
        }
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ValidifyGeneratedRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}