//HintName: ValidifyGeneratedRegistration.g.cs
// <auto-generated/>
#nullable enable
namespace Validify
{
    using global::Microsoft.Extensions.DependencyInjection.Extensions;

    /// <summary>Auto-generated FluentValidation validator registrations.</summary>
    public static class ValidifyGeneratedRegistration
    {
        /// <summary>Registers every discovered FluentValidation validator.</summary>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddValidifyValidators(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped)
        {
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::FluentValidation.IValidator<global::Sample.Models.A>), typeof(global::Sample.Validators.DualValidator), lifetime));
            services.TryAdd(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::FluentValidation.IValidator<global::Sample.Models.B>), typeof(global::Sample.Validators.DualValidator), lifetime));
            return services;
        }
    }
}
