//HintName: ValidifyGeneratedRegistration.g.cs
// <auto-generated/>
#nullable enable
namespace Microsoft.Extensions.DependencyInjection
{
    using global::Microsoft.Extensions.DependencyInjection.Extensions;

    /// <summary>Auto-generated FluentValidation validator registrations.</summary>
    public static class ValidifyGeneratedRegistration
    {
        /// <summary>Registers every discovered FluentValidation validator.</summary>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddValidifyValidators(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped)
        {
            return services;
        }
    }
}
